BBPATH .= ":${LAYERDIR}"

BBFILES += "${LAYERDIR}/recipes*/*/*.bb ${LAYERDIR}/recipes*/*/*.bbappend ${LAYERDIR}/images/*.bb"

BBFILE_COLLECTIONS += "meta-advantech-imx8"
BBFILE_PATTERN_meta-advantech-imx8 := "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-advantech-imx8 = "16"

LAYERSERIES_COMPAT_meta-advantech-imx8 = "scarthgap"
